{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codelang.check",
    "module": "checkplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "checkplugin-1.0.0.jar",
          "url": "checkplugin-1.0.0.jar",
          "size": 37598,
          "sha512": "560bfca1ed59eae0e7f98d5b74a784dcf6761cabaca1a1122b60c38d41d5b449592cca2567c1710026dd46728124a1be5e723f50a6b2f602248df06e0b86eff7",
          "sha256": "78eaae1aa0c832e49ea7618a0c234cec3191453ea70b9446c20d309add47fbfc",
          "sha1": "436e036cb5b1c9c5a3498124494c27bffa5f318e",
          "md5": "3f5c911133b6bc1b4532214c1dfb6b03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "checkplugin-1.0.0.jar",
          "url": "checkplugin-1.0.0.jar",
          "size": 37598,
          "sha512": "560bfca1ed59eae0e7f98d5b74a784dcf6761cabaca1a1122b60c38d41d5b449592cca2567c1710026dd46728124a1be5e723f50a6b2f602248df06e0b86eff7",
          "sha256": "78eaae1aa0c832e49ea7618a0c234cec3191453ea70b9446c20d309add47fbfc",
          "sha1": "436e036cb5b1c9c5a3498124494c27bffa5f318e",
          "md5": "3f5c911133b6bc1b4532214c1dfb6b03"
        }
      ]
    }
  ]
}
